version: '3'

services:
  # 后端服务
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./logs:/app/logs
      - node_modules_server:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    restart: always

  # 前端服务
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: always

volumes:
  node_modules_server:
  node_modules_client:
